name: android_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.0

dependencies:
  carousel_slider: ^5.1.1
  dio: ^5.9.0
  flutter:
    sdk: flutter
  go_router: ^16.2.4
  open_file: ^3.5.10
  path_provider: ^2.1.5
  photo_view: ^0.15.0
  smooth_page_indicator: ^1.2.1
  syncfusion_flutter_pdfviewer: ^31.2.3

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/integrantes/
    - assets/files/
    - assets/conclusiones/
